---
- name: Playbook to configure AAP
  hosts: localhost
  gather_facts: false
 
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars

  tasks:
    !
    !
    - name: Import role-aap-object-workflow-template
      ansible.builtin.include_role:
        name: role-aap-object-workflow-template
      vars:
        workflow: true
        workflow_name: "{{ appc_config_backup_workflow }}"
        inventory_name: "{{ inventory_name }}"
        organization_name: "{{ organization_name }}"
        job_tmplts_list: "{{ appc_config_backup_job_tmplts_list }}"
        nodes_linking_list: 
          - "{{ cisco_to_junos }}"
          - "{{ junos_to_fortios }}"
          - "{{ fortios_to_f5 }}"
    !
    !