---

- name: Create workflow template
  ansible.controller.workflow_job_template:
    name: "{{ workflow_name }}"
    inventory: "{{ inventory_name }}"
    organization: "{{ organization_name }}"
    state: present
    description: "{{ common_description }}"
  register: rhel_workflow 

# Create workflow nodes
- name: Create workflow nodes 
  ansible.controller.workflow_job_template_node:
    workflow: "{{ workflow_name }}"
    identifier: "{{ item }}"
    organization: "{{ organization_name }}"
    unified_job_template: "{{ item }}"
    state: present
  loop: "{{ appc_config_backup_job_tmplts_list }}"

# - name: "Create approval node"
#   awx.awx.workflow_job_template_node:
#     workflow: "{{ workflow_name }}"
#     identifier: "{{ rhel_change_approval_node_name }}"
#     organization: "{{ organization_name }}"
#     state: present
#     approval_node:
#         description: "Proceed with change?"
#         name: "{{ rhel_change_approval_node_name }}"
#         timeout: 3600 # The amount of time (in seconds) before the approval node expires and fails.

# # Stitch job templates into a workflow
- name: "Link {{ item[0] }} workflow node to {{ item[1] }} node"
  ansible.controller.workflow_job_template_node:
    workflow: "{{ workflow_name }}"
    identifier: "{{ item[0] }}"
    organization: "{{ organization_name }}"
    success_nodes: 
      - "{{ item[1] }}"  # When successful moves to this
    loop: "{{ nodes_linking_list }}"
